Upgrade code to work in PHP8 or greater
voku/portable-ascii pull request #87
Opened 2023-01-05 17:05 UTC by summercms

Fixes: https://github.com/voku/portable-ascii/issues/86

This repo doesn't work in PHP 8, 8.1 or 8.2 due to the namespaces not being Capitalized.

* Have updated the GitHub workflows up to php 8.2
* Have updated the namespaces.
* Have updated composer.json and removed php 7 as security updates ended in 28 November 2022.
* Have updated readme with new namespaces

Need to update the connecting repos now.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/voku/simple_html_dom/95)

2023-01-07 12:36 UTC, summercms commented
The namespace is causing this issue, I show you screenshot with a Laravel Facades:

![image](https://user-images.githubusercontent.com/57409060/211150478-4cd5b446-c303-44e2-81f2-cbb3e43bd50d.png)

Everything was working fine in php 7.4 and Laravel 5 LTS. Then upgraded and tested it in PHP 8.0, 8.1 and 8.2 with Laravel 9 LTS and it doesn't like the lowercase namespaces at all.

(*) - Using and tested it in latest composer as well.

The 5 pull requests I have created fixes this issue.

Yes you are correct all the packages need to have a `major` semantic version update. But it should be a `major` update anyway because the package is being updated from php 7 (discounted) to php 8.

p.s. I did send Voku a DM in his twitter but he still not replied.

Comment: https://github.com/voku/simple_html_dom/pull/95#issuecomment-1374465561

2023-01-07 20:13 UTC, summercms commented
Done some digging.

This package fails PSR-1 Chapter 3 rules for Namespaces and Class Names:

> Class names MUST be declared in `StudlyCaps`.

Can share a link to the PSR Spec here: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md#3-namespace-and-class-names

2023-01-08 11:01 UTC, GrahamCampbell requested changes
👎 These changes are incorrect and totally unnecessary.

2023-01-08 14:09 UTC, summercms commented
@GrahamCampbell 

You work at Laravel (want to hear your insight please). Where do you think the issue is getting created?

Was totally fine with Laravel 5 LTS + PHP 7.4, then upgraded to Laravel 9 LTS and tried PHP 8.0.19 and 8.2.0 and got this issue, haven't changed any of the namespaces in the upgrade. Plus using latest composer version.

Laravel 9 LTS can find all the other vendor files except this package with the lowercase namespaces. When I manually convert the namespaces to `StudlyCaps` Laravel 9 LTS can find it no problem ?

Any suggestions would be helpful.

2023-01-08 15:54 UTC, summercms commented
Closing this as looks like an issue with the auto-discovery loader in the Laravel CMS and not an issue with this package, Laravel or PHP.

2023-01-08 15:54 UTC, closed without merging